name: ffmpeg_kit_flutter_new_min
description: FFmpeg Kit Minimal for Flutter. Supports Android, iOS and macOS platforms.
repository: https://github.com/sk3llo/ffmpeg_kit_flutter
homepage: https://github.com/sk3llo/ffmpeg_kit_flutter
version: 2.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.antonkarpenko.ffmpegkit
        pluginClass: FFmpegKitFlutterPlugin
      ios:
        pluginClass: FFmpegKitFlutterPlugin
      macos:
        pluginClass: FFmpegKitFlutterPlugin

dependencies:
  ffmpeg_kit_flutter_platform_interface: ^0.2.1
  plugin_platform_interface: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
